### ISSUE TITLE
Question about Networktraffic from Speedchecker-App to aaronjwood.com

### ISSUE THREAD

**Issue by Miriam-cpu** [aaronjwood/aaronjwood.com#3]
Hi, sorry for misusing this path to contact you, but did not find another way. We are currently analyzing the networktraffic of some Android-Apps, among them This one: com.vtool.speedtest.speedcheck.internet
For some reason the app calls the URL yourip.aaronjwood.com. We just wondered, what this connection is for. 

btw "we" that is a nonprofit-project based in Berlin, Germany, known as the "appchecker". We basicly bulk analyze Android-Apps for data-leaks and contacts to tracking thirdparties. See more here: https://appcheck.mobilsicher.de/

If you like you can contact me directly via mail: m.ruhenstroth@mobilsicher.de
Best Miriam

**Comment by aaronjwood** [comment]
Hi, that is a tiny service which I wrote to return back a WAN IP https://github.com/aaronjwood/public-ip-api
